version: '3.6'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms12g -Xmx12g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - "elastic"

volumes:
  elastic_data:

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.15.2
#    ports:
#      - 5044:5044
#    environment:
#      - monitoring.elasticsearch.hosts=http://elastic:9200
#      - xpack.monitoring.enabled=false
#    volumes:
#      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
