#logging.level: debug

filebeat.inputs:
  - type: docker
    containers.ids:
      - '*'
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: [ "http://elastic:9200" ]
  username: "elastic"
  password: "mu8yie4mah3So9oh"