version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:14.3.3-ce.0
    ports:
      - 22:22
      - 80:80
      - 443:443
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/logs/var/log/gitlab
      - gitlab_config:/config/etc/gitlab
      #- $GITLAB_HOME/certs/apache-global.crt:/etc/gitlab/ssl/gitlab-server.crt
      #- $GITLAB_HOME/certs/apache-global.key:/etc/gitlab/ssl/gitlab-server.key
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb

  gitlab-runner:
    image: gitlab/gitlab-runner:v14.3.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    deploy:
      mode: replicated
      replicas: 4

configs:
  gitlab:
    file: ./gitlab.rb

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:
  gitlab_runner_config: