version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:14.3.2-ce.0
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
      #- $GITLAB_HOME/certs/apache-global.crt:/etc/gitlab/ssl/gitlab-server.crt
      #- $GITLAB_HOME/certs/apache-global.key:/etc/gitlab/ssl/gitlab-server.key
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb

  gitlab-runner:
    image: gitlab/gitlab-runner:v14.3.2
    deploy:
      mode: replicated
      replicas: 4

configs:
  gitlab:
    file: ./gitlab.rb
