version: '2'

services:

  postgresql:
    image: postgres:13.2-alpine
    network_mode: "host"
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth_db,data_db


