version: '3.3'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    command: ["-e", "--strict.perms=false"]
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

