filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'

output.elasticsearch:
  hosts: ["http://192.168.122.38:9200"]

#output.logstash:
#  hosts: [192.168.122.38:5044]
