version: '3.6'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    #volumes:
    #  - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
