
global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'iam-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'device-controller'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8090']
